"""Added client_id field to Messages table

Revision ID: 31d68f9eb273
Revises: 851a704a2aa3
Create Date: 2026-09-28 20:24:28.080984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31d68f9eb273'
down_revision: Union[str, Sequence[str], None] = '851a704a2aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('client_id', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'client_id')
    # ### end Alembic commands ###
