"""Added ImgsInMSGS table

Revision ID: 48f998960837
Revises: 7ac0f6ebad75
Create Date: 2026-09-23 10:10:24.865459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48f998960837'
down_revision: Union[str, Sequence[str], None] = '7ac0f6ebad75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imgs_in_msgs',
    sa.Column('pic_path', sa.String(length=128), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['msg_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imgs_in_msgs')
    # ### end Alembic commands ###
