"""Added do_email_notifications field in Users table

Revision ID: 490988e8eb7d
Revises: 31d68f9eb273
Create Date: 2026-10-01 14:15:20.181992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '490988e8eb7d'
down_revision: Union[str, Sequence[str], None] = '31d68f9eb273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('do_email_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'do_email_notifications')
    # ### end Alembic commands ###
