"""is pinned field in posts table

Revision ID: 55c10e6108ba
Revises: 7fdfaeb90916
Create Date: 2026-08-11 20:50:40.142524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '55c10e6108ba'
down_revision: Union[str, Sequence[str], None] = '7fdfaeb90916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_pinned', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_pinned')
    # ### end Alembic commands ###
