"""allow comments in posts table

Revision ID: 7fdfaeb90916
Revises: c34274f3f9c7
Create Date: 2026-08-11 14:02:12.769462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fdfaeb90916'
down_revision: Union[str, Sequence[str], None] = 'c34274f3f9c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('allow_comments', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'allow_comments')
    # ### end Alembic commands ###
