"""Added created at field in Messages and ImgsInMsgs tables

Revision ID: 851a704a2aa3
Revises: 48f998960837
Create Date: 2026-09-23 15:08:01.049623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '851a704a2aa3'
down_revision: Union[str, Sequence[str], None] = '48f998960837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imgs_in_msgs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    op.drop_column('imgs_in_msgs', 'created_at')
    # ### end Alembic commands ###
